Add actionless flag
Signed-off-by: roeiK-wix <roeik@wix.com>

Revert changes

Signed-off-by: roeiK-wix <roeik@wix.com>

Refactor dry flag

Signed-off-by: roeiK-wix <roeik@wix.com>

Revert merge changes

Signed-off-by: roeiK-wix <roeik@wix.com>

Revert changes

Signed-off-by: roeiK-wix <roeik@wix.com>

Remove new line

Signed-off-by: roeiK-wix <roeik@wix.com>

Refactor dry flag

Signed-off-by: roeiK-wix <roeik@wix.com>

Migrate to Python 3.6 as the baseline

Closes #208

Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version 1.8.1 -> 1.9.0

Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
Signed-off-by: roeiK-wix <roeik@wix.com>

fix: validate_vars returns nothing, but must return convert_vars result (#213)

* fix: validate_vars returns nothing, but must return convert_vars result

Signed-off-by: Nikita Savitsky <nikita.savitsky@behavox.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version 1.9.0 -> 1.9.1

Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
Signed-off-by: roeiK-wix <roeik@wix.com>

Fixed typos and a couple of formatting changes (#223)

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Removed ChaosIQ Dependency (#225)

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Changed Link Address (#226)

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Add Close Stale Issue job to CI (#224)

* Only runs in Debug mode for now

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Fix input names on `close_stale_issues` (#227)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Activate setting issues to Stale on a schedule (#228)

* Activate setting issues to Stale on a schedule

Signed-off-by: Ciaran Evans <ciaran@reliably.com>

* Update Changelog

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump up Stale Issues actions to 200 from 300 (#229)

* The Stale action by default runs 30 actions (API calls against GitHub)
* Bumping this to 200 as 30 is quite restrictive
* GitHub limit is 1000 calls per hour per repository so we wont hit this limit

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Fix issue where PyPi being slow meant Docker images used older versions (#231)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version 1.9.1 -> 1.9.2

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Removed "version" key from .json experiment (#233)

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Fix `reognised` to `recognised` (#234)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Changed multiple references from  to  (#235)

* Changes multiple references from  to

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

* Added Backwards Compatability

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

* Added Tests for Backward Compatability

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

* Formatting Changes

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

* Formatting Changes

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

* Changed Formatting

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Fixed Typo (#236)

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version from 1.9.2 -> 1.9.3

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Remove no-dry flag

Signed-off-by: roeiK-wix <roeik@wix.com>

Move from Pylama/Pycodestyle to black, flake8, and isort (#238)

Adding tests for Python 3.9
Modifying the build workflow to run building, testing, and linting
Adding a Makefile to abstract away common commands
Updating the README to specify how to use the new formatting etc.

Signed-off-by: roeiK-wix <roeik@wix.com>

Pin `chaostoolkit-lib` to `~=1.21` (#240)

Signed-off-by: roeiK-wix <roeik@wix.com>

Apply , ./chaostoolkit/cli.py:7:1: F811 redefinition of unused 'Any' from line 5
./chaostoolkit/cli.py:7:1: F811 redefinition of unused 'Dict' from line 5
./chaostoolkit/cli.py:7:1: F811 redefinition of unused 'List' from line 5
./chaostoolkit/cli.py:23:1: F401 'chaoslib.types.Strategy' imported but unused
./chaostoolkit/cli.py:24:23: E231 missing whitespace after ','
./chaostoolkit/cli.py:25:1: F811 redefinition of unused 'click' from line 9
./chaostoolkit/cli.py:174:10: E127 continuation line over-indented for visual indent, and  (#239)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Run `pyupgrade --py36-plus` (#241)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Fix broken README.md link and make comment about CHANGELOG (#242)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version from 1.9.3 -> 1.9.4

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version from 1.9.4 -> 1.9.5

* Fix version extraction

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Bump version from 1.9.5 -> 1.9.6

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Add Check PR workflow to GitHub Actions (#243)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Rearranged `pip install` in Makefile (#244)

* Rearranged `pip install` in Makefile

Signed-off-by: Charlie Moon <charlie@chaosiq.io>

* Updated Changelog

Signed-off-by: Charlie Moon <charlie@chaosiq.io>
Signed-off-by: roeiK-wix <roeik@wix.com>

Apply , ./chaostoolkit/cli.py:5:1: F811 redefinition of unused 'Any' from line 3
./chaostoolkit/cli.py:5:1: F811 redefinition of unused 'Dict' from line 3
./chaostoolkit/cli.py:5:1: F811 redefinition of unused 'List' from line 3
./chaostoolkit/cli.py:21:1: F401 'chaoslib.types.Strategy' imported but unused
./chaostoolkit/cli.py:22:23: E231 missing whitespace after ','
./chaostoolkit/cli.py:23:1: F811 redefinition of unused 'click' from line 7
./chaostoolkit/cli.py:172:10: E127 continuation line over-indented for visual indent, and  (#239)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Add more test for the new dry flags

Signed-off-by: roeiK-wix <roeik@wix.com>

Fix test_cli

Signed-off-by: roeiK-wix <roeik@wix.com>

Add to changelog

Signed-off-by: roeiK-wix <roeik@wix.com>

Move from Pylama/Pycodestyle to black, flake8, and isort (#238)

Adding tests for Python 3.9
Modifying the build workflow to run building, testing, and linting
Adding a Makefile to abstract away common commands
Updating the README to specify how to use the new formatting etc.

Signed-off-by: roeiK-wix <roeik@wix.com>

Pin `chaostoolkit-lib` to `~=1.21` (#240)

Signed-off-by: roeiK-wix <roeik@wix.com>

Apply , ./tests/test_cli.py:28:1: E302 expected 2 blank lines, found 1
./chaostoolkit/cli.py:261:5: E303 too many blank lines (2), and  (#239)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>

Run  (#241)

Signed-off-by: Ciaran Evans <ciaran@reliably.com>
Signed-off-by: roeiK-wix <roeik@wix.com>