Apply , ./chaostoolkit/cli.py:5:1: F811 redefinition of unused 'Any' from line 3 ./chaostoolkit/cli.py:5:1: F811 redefinition of unused 'Dict' from line 3 ./chaostoolkit/cli.py:5:1: F811 redefinition of unused 'List' from line 3 ./chaostoolkit/cli.py:21:1: F401 'chaoslib.types.Strategy' imported but unused ./chaostoolkit/cli.py:22:23: E231 missing whitespace after ',' ./chaostoolkit/cli.py:23:1: F811 redefinition of unused 'click' from line 7 ./chaostoolkit/cli.py:172:10: E127 continuation line over-indented for visual indent, and  (#239)
Signed-off-by: Ciaran Evans <ciaran@reliably.com>